name: Deploy Admin to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.email "joel.odufu"gmail.com"
          git config --global user.name "joelodufu"
          npm install -g gh-pages
          gh-pages -d build
